import { Card } from "../types/card";

export const CARD_ITEMS: Card[] = [
  {
    title: "모노레포1",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-04-29"),
    commentsCount: 2,
    filesCount: 7,
  },
  {
    title: "모노레포2",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-05-11"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포3",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-05-30"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포4",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-05-25"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포5",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-03-15"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포6",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-04-15"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포7",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    deadline: new Date("2024-05-18"),
    commentsCount: 0,
    filesCount: 0,
  },
  {
    title: "모노레포8",
    subtitle: "Nx, npm workspaces",
    progressRate: [2, 2],
    progressColor: "black",
    commentsCount: 0,
    filesCount: 0,
  },
];
